---
# Papita Transactions Model Logger Configuration
version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

loggers:
  papita_txnsmodel:
    level: INFO
    handlers:
      - console
    propagate: no

  papita_txnsregistrar:
    level: INFO
    handlers:
      - console
    propagate: no

  papita_txnregistrar_plugins:
    level: INFO
    handlers:
      - console
    propagate: no
